version: "3"
services:
  minh-fe:
    image: heaty566/capstone-minh-fe:latest
    expose:
      - 3000
    networks:
      - mono
  minh-server:
    image: minhptq/capstone-minh-server:latest
    depends_on:
      - minh-db
    env_file:
      - .env
    expose:
      - 8080
    networks:
      - mono
  minh-db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=capstone
    expose:
      - 3306
networks:
  mono:
    external: true
