server:
  port: 8082

spring:
  application:
    name: CV-SERVICE
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/springboot-microservice-realm

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
